name: Deploy production

on:
    push:
        branches: ["main"]
jobs:
    build:
        name: common-deploy
        uses: ./.github/workflows/deploy.common.yml
        with:
            awsRegion: ap-southeast-1
            s3BucketName: coinmarketscore-web
            s3Prefix: hercules.coinmarketscore.io/
            cloudfrontId: E1LFVHPNUQLSV8
        secrets: inherit