name: Deploy hercules test(chart) code

on:
    workflow_call:
        inputs:
            awsRegion:
                required: true
                type: string
            s3BucketName:
                required: true
                type: string
            s3Prefix:
                required: true
                type: string
            cloudfrontId:
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: package-lock.json  # frontend 디렉토리의 잠금 파일을 사용
            - run: |
                  npm ci --force
                  NODE_OPTIONS=--openssl-legacy-provider npm run build
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ inputs.awsRegion }}
            - name: Sync to AWS S3
              run: aws s3 sync --delete ./dist s3://${{ inputs.s3BucketName }}/${{ inputs.s3Prefix }}
            - name: Invalidate Cloudfront cache
              run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfrontId }} --paths "/*"